name: Build and Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.12.x
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test
        run: make test

  build:
    name: Build
    strategy:
      matrix:
        go-version:
          - 1.12.x
    runs-on: ubuntu-18.04
    needs:
      - test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: make
